#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker01"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "d19f9b3883734daf816c46c3c2036c87" }
]

[assets]
directory = "./public"
